version: '3'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_data:/data/db
  application:
    image: application
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: application
    hostname: frontend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
      MONGO_URL: "mongodb"
      MONGO_PORT: ${MONGO_PORT}

volumes:
  mongodb_data:
