name: Deno Lint

on:
  push:
    paths:
      - '**.ts'
      - '**.tsx'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Deno
        uses: denoland/setup-deno@main
        with:
          deno-version: v1.x

      - name: Lint with Deno
        run: deno lint
